# Generated by Django 3.0.4 on 2021-03-03 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='ChocolateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Flavors',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='sitio/static/images/no-img.jpg', upload_to='gallery')),
                ('name', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='POS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('direction', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telephone', models.CharField(max_length=12)),
                ('logo', models.ImageField(default='sitio/static/images/no-img.jpg', upload_to='logo')),
            ],
            options={
                'verbose_name_plural': 'POS',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Category')),
                ('chocolateType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.ChocolateType')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Flavor')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.Image')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
