# Generated by Django 3.0.4 on 2021-02-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='descripcion',
            field=models.CharField(default='2021-01-01', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='nombre',
            field=models.CharField(default='nombre', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chocolatetype',
            name='nombre',
            field=models.CharField(default='namemdk', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavor',
            name='descripcion',
            field=models.CharField(default='dakdjfkad', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flavor',
            name='nombre',
            field=models.CharField(default='1333', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='nombre',
            field=models.CharField(default='askfjalsd', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='direccion',
            field=models.CharField(default='asfasdfa', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pos',
            name='nombre',
            field=models.CharField(default='asdfqwer', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='descriccion',
            field=models.CharField(default='2sakjasdjfasñdf', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nombre',
            field=models.CharField(default='asfasdf', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
