# Generated by Django 3.0.4 on 2021-04-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
