# Generated by Django 3.0.4 on 2021-03-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(default='sitio/static/img/no-img.png', upload_to='gallery'),
        ),
    ]
