# Generated by Django 3.0.4 on 2021-02-22 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_auto_20210211_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriccion',
            new_name='descripcion',
        ),
    ]
