# Generated by Django 3.0.4 on 2021-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20210702_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fecha_creacion',
            field=models.DateField(default='2021-07-02'),
            preserve_default=False,
        ),
    ]
