# Generated by Django 3.0.4 on 2021-07-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_product_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='fecha_creacion',
            new_name='year_of_validity',
        ),
    ]
