# Generated by Django 3.0.4 on 2021-07-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_auto_20210704_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='year',
        ),
    ]
