# Generated by Django 3.0.4 on 2021-07-04 19:56

from django.db import migrations, models
import sitio.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_remove_product_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2021)),
                ('approve_ts', sitio.models.ApproveStopModelField(blank=True, null=True, verbose_name='Approve place')),
            ],
        ),
    ]
