# Generated by Django 3.0.4 on 2021-07-04 20:14

from django.db import migrations
import sitio.models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='approve_ts',
        ),
        migrations.AddField(
            model_name='stop',
            name='year_of_validity',
            field=sitio.models.ApproveStopModelField(blank=True, null=True, verbose_name='Year of Validity'),
        ),
    ]
