# Generated by Django 3.0.4 on 2021-07-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_auto_20210704_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='year',
        ),
    ]
