# Generated by Django 3.0.4 on 2021-07-04 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0011_remove_stop_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stop',
            new_name='PruebaFecha',
        ),
    ]
